AndelaOSP/art-dashboard

.circleci/config.yml
.coveralls.yml
README.md

- Redirect coveralls to default `develop` branch
[Delivers:#157929770]
Redirects the coveralls badge to the develop branch
Change the coveralls badge on the README.md to point to the develop branch
N/A
[#157929770](https://www.pivotaltracker.com/story/show/157929770)
The coveralls badge had originally been directed to the then default `master` branch
N/A
N/A
N/A
N/A
N/A

ch(coverals)Redirect branch to develop

---

src/_components/ModelNumber/ModelNumberContainer.jsx
src/components/ModelNumber/ModelNumberComponent.jsx

Fixes a bug in retrieving asset makes
On the asset make dropdown, the existing asset makes are not being listed.
On login, go to assets. Click on the + plus icon on the asset model number, which opens the model number modal. Click on the asset makes dropdown and  the existing makes should be visible.
https://www.pivotaltracker.com/story/show/158862563
N/A
N/A
N/A
N/A
Branch | PR

[#158862563] fix bug in add model number component

---

src/_components/AssetTypes/AddAssetTypesContainer.jsx
src/_reducers/initialState.js
src/_reducers/subcategory.reducer.js
src/components/AssetsSubCategoriesComponent.jsx

Fix pagination for subcategories that was messed up
- add separate attribute in subcategories store
- fix pagination issue on AssetSubCategoriesComponent
- Login and check the subcategories page. The pagination should show the 1st 10 results. The next page should show the next 4 results.
- Go to Assets page. Click on the `+` on the Asset Types column. the subcategories dropdown should have all 14 subcategories.
[#158911251](https://www.pivotaltracker.com/story/show/158911251)
n/a
n/a
n/a
n/a
Branch | PR

[#158911251] Fix Subcategories Pagination Issue

---

src/_components/Assets/AddAssetContainer.jsx

This PR ensures the values following a drop-down option are subsequently changed whenever the drop-down option is changed.
- As a user adding an asset, after filling in all the other drop-down fields and I select a different category, then all other drop-down fields should be cleared. 
- When I change a subcategory and not category all other dropdowns after the subcategory field should be cleared. Similarly, with Asset Types and Asset Makes and Model Numbers.
- Pull the branch
- Click on assets on the Side Menu. Once the assets table is displayed, click on the plus sign to add an asset.
- Add a `category`, `subcategory`, `type`, `make` then `model`. Change the `type` option, the `make` and `model` should change at this point. Changing the `category` option should have the same effect on …

feature(dropdown-fields): Clear all relevant fields after a dropdown value is changed

---

src/_components/AssetMake/AssetMakeContainer.jsx
src/_components/AssetTypes/AddAssetTypesContainer.jsx
src/_components/Category/CategoryContainer.jsx
src/_components/ModelNumber/ModelNumberContainer.jsx
src/_components/SubCategory/AddSubCategoriesContainer.jsx
src/_css/sharedStyling.scss

Fixes display of error toast for  the modal components
1. Visit asset lists page 
2. Click on the plus icon to add  a new category 
3. Add an existing category
The modal closes and the error is displayed as a toast message.
The error should be displayed on the modal
The modal should not close unless the user closes it.
Once logged in, go to assets page. Click on any of the plus icons and on the opened model add an existing item, this should generate an error. The toast component will be displayed on the modal and the modal will not close until prompted by user.
https://www.pivotaltracker.com/story/show/159462759
N/A
N/A
N/A
N/A
Branch | PR

#159462759 Users should see errors on the modal.

---

src/__test__/components/NavBarComponent.test.js
src/_css/NavBarComponent.scss
src/components/NavBarComponent.jsx

Enables logged in users to view the navigation bar by default when they log in.
**Scenario:** Users should be able to see the navigation bar by default.
**Given**  An admin on the homepage
**Then** I should be able to see the navigation bar and close it when I wish to hide it.
- Start the application
- Log in
- View the changes in the /dashboard url
[159465815](https://www.pivotaltracker.com/story/show/159465815)
N/A
N/A
N/A
N/A
N/A

#159465815 Feature: Users should be able to see the navigation bar by default

---

package-lock.json
package.json
src/components/AllocationsComponent.jsx
src/components/AssetCategoriesComponent.jsx
src/components/AssetSpecs/AssetSpecsComponent.jsx
src/components/AssetsSubCategoriesComponent.jsx
src/components/TableRowComponent.jsx
src/components/User/UserFeedbackComponent.jsx
src/components/common/DropdownComponent.jsx

- removes id column in asset specs
- removes id column in asset and subcategories
- renames created at the column to date
- changes date format in the feedback table
- Remove the ID column in Asset specs, asset subcategories, asset categories.
- Rename the CreatedAt column to date in Allocations.
- Change the date format in the user feedback table.
- View the following sub menus
- Asset specs 
- asset sub categories
- asset  categories.
[#159467964](https://www.pivotaltracker.com/story/show/159467964)
- moment js

chore(cleanup): table data cleanup

---

src/__test__/_components/AddSubCategoriesContainer.test.js
src/__test__/_components/CategoryContainer.test.js
src/__test__/_components/ModelNumberContainer.test.js
src/_components/RoutesComponent.jsx
src/components/AssetDetailComponent.jsx
src/components/AssetDetailContent.jsx
src/components/AssetsTableContent.jsx
src/components/NavBarComponent.jsx

Fixes how blank data is displayed on the asset list and asset detail pages
* If the asset code or the serial number is null from the response, display `-`
* Swap the `Category` and `Subcategory` headers.
* Start the application
* Log in
* Navigate to the `Asset List` link
* View an asset with an empty `Serial Number` or `Asset Code`
[159468670](https://www.pivotaltracker.com/story/show/159468670)
N/A
N/A
N/A
N/A
N/A

#159468670 Fix asset list and asset detail display

---

src/__test__/AddAssetMakeComponent.test.js
src/_components/AssetMake/AssetMakeContainer.jsx
src/_components/AssetTypes/AddAssetTypesContainer.jsx
src/_components/ModelNumber/ModelNumberContainer.jsx
src/_components/SubCategory/AddSubCategoriesContainer.jsx
src/_css/ModalComponent.scss
src/components/AssetDescriptionComponent.jsx
src/components/AssetDetailComponent.jsx
src/components/AssetMake/AddAssetMakeComponent.jsx
src/components/AssetTypes/AddAssetTypesComponent.jsx
src/components/Category/AddCategoryComponent.jsx
src/components/ModelNumber/ModelNumberComponent.jsx
src/components/SubCategory/AddSubCategoryComponent.jsx
src/components/common/ModalComponent.jsx

- Fixes the dropdown bug so that they should detect change in selected option.
**Expected**
- Case 1: On clicking the + icons on the Asset lists page, the dropdown on displayed modal popup should detect a change in selected value and display it on the input field.
- Case 2: When assigning an asset, user should be able to select an email on the dropdown.
**Current**
- Once a value is selected, the dropdown does not detect the change and value not displayed as the selected option.
This  affects:
_Model Number,_
_Asset Make,_
_Asset type_
_Sub Category_
_Assign Asset_
- Once logged in, on the Assets Lists page, click on any of the + icons. 
- On the modal displayed, try changing value of selected option on the dropdown. The selected option should be displayed on the input field.
- …

#159742621 Fix dropdowns to detect selected option

---

src/_components/Assets/AddAssetContainer.jsx
src/components/Assets/AddAssetComponent.jsx
src/components/Assets/FilterAssetComponent.js

- Disallow the user from continue/clicking `Next` without filling in Category, Subcategory, Asset Type and Asset Make
- Disallow the user from saving without filling model number, asset tag and serial number
- use disabled attribute in Button component
- add function to check which page is being validated
- add button disable when user has not filled in fields in form.
- `npm test` OR 
- Login, click on `ADD ASSET` on the navbar
- The `NEXT` button is disabled by default.
- Fill in the Category, Subcategory, Asset Type and Asset Make. The `NEXT` button will be enabled. If you change any these, Category, Subcategory, Asset Type and Asset Make and some fields become empty then the `NEXT` button is disabled. This is the same for page 2, `Fill out device specs` …

#159519715  Field Validation On Asset Modal

---

src/components/AssetsTableContent.jsx

- change the url to use the asset id instead of asset serial number
- change the `AssetsTableContent` component to use asset `id` instead of `serial_number`
- Login to ART, 
- Go to asset list page.
- Click on an asset. The url should be a number and not a alphanumeric text
`assets/{id}/view` e.g. `assets/154/view`
[#159958261](https://www.pivotaltracker.com/story/show/159958261)
n/a
n/a
n/a
n/a
Branch | PR

#159958261 Change url from serial number to asset id

---

src/components/AssetsTableContent.jsx

- change the url to use the uuid instead of asset id
- change the `AssetsTableContent` component to use asset `uuid` instead of `id`
- Login to ART, 
- Go to asset list page.
- Click on an asset.
`assets/{uuid}/view` e.g. `assets/c0b8e495-0d7b-435a-a36e-83b79e3453e8/view`
[#159958261](https://www.pivotaltracker.com/story/show/159958261)
n/a
n/a
n/a
Branch | PR

#159958261 Change to uuid instead of asset id on url

---

src/_css/sharedStyling.scss
src/components/AssetCategoriesComponent.jsx
src/components/AssetMake/AssetMakeComponent.jsx
src/components/AssetModels/AssetModelsComponent.jsx
src/components/AssetTypesComponent.jsx
src/components/AssetsSubCategoriesComponent.jsx
src/components/AssetsTableContent.jsx

- Remove plus icons in assets list page
- remove plus icons in assets list
- place plus icons in respective list pages
- Login to ART
- Go to the assets list page. The plus icons are no longer there.
- Go to the Categories, SubCategories, Asset Types, Asset Makes, and Model Number pages.
- There is a blue button on the right for each page to add a category, sub category etc
[#159880567](https://www.pivotaltracker.com/story/show/159880567)
n/a
n/a
n/a
n/a
Branch | PR

#159880567 Remove plus icons in assets list page

---

src/__test__/AssetTypesComponent.test.js
src/__test__/AssetsAllocationHistory.test.js
src/__test__/AssetsTableContent.test.js
src/__test__/IncidenceReportsComponent.test.js
src/__test__/TableRowComponent.test.js
src/__test__/components/AssetModelsComponent.test.js
src/__test__/components/UserFeedbackComponent.test.js
src/components/AssetsTableContent.jsx
src/components/TableRowComponent.jsx

- Use `withRouter` when navigating to view asset or user
- add `withRouter` HOC in TableRowComponent
- remove tests affected by TableRow
- rename component import name to TableRow
- npm test 
- Login to ART, navigate to assets. Click on one asset.
- The asset detail page should be loaded
[#160252137](https://www.pivotaltracker.com/story/show/160252137)
n/a
n/a
n/a
n/a
Branch | PR

160252137 Refactor routing to specific asset or user

---

src/__test__/AssetDescriptionComponent.test.js
src/__test__/AssetDetailComponent.test.js
src/_css/AssetDetailContent.scss
src/components/AssetDescriptionComponent.jsx
src/components/AssetDetailComponent.jsx
src/components/TableRowComponent.jsx

- It prevents fetching data for asset details in the store.
- Prevent fetching asset details for an asset whose details are already in the store
- Load asset list and click on an asset. It should load the asset details from the store.
- Copy the URL for the asset and open it on a guest window. It should fetch the asset details.
#[160253989](https://www.pivotaltracker.com/story/show/160253989)
- none
- none
- none
- none

#160253989 Prevent fetching asset details if they are in the store

---

src/__test__/AssetDescriptionComponent.test.js
src/_css/AssetDescriptionComponent.scss
src/_css/AssetDetailContent.scss
src/components/AssetDescriptionComponent.jsx

Shows relevant data on asset specs rather than dummy data
- Refactor component to gain access to data from the store
- Refactor tests to accommodate new changes
On the `asset list` page, click on a single `asset` to view its `details`. On the same page, `asset specs` can be viewed if they are available.
[#160197002](https://www.pivotaltracker.com/n/projects/2146417/stories/160197002)
N/A
N/A
N/A
N/A
Branch | PR
- After implementing changes on PR

#160197002 Show relevant data on asset specs

---

src/_css/AssetDetailContent.scss
src/components/AssetDetailComponent.jsx
src/components/AssetDetailContent.jsx

Fix data displayed in the asset detail page
```gherkin
1. Go to asset list page
2. Click on one of the assets (note the asset make, category, subcategory)
3. When the asset details load note the details on the page.
4. Go back to asset details page
5. Repeat steps 1-3 for a different asset
- The details on the asset list page should match the details  of the asset loaded.
- The asset loads, and makes load the same data for all the assets.
```
* Log in
* Navigate to the assets page
* Click on one of the assets to view details
* Go back to assets page
* Click on another asset to see if the details displayed are correct
[160614085](https://www.pivotaltracker.com/story/show/160614085)
N/A
N/A
N/A
N/A
N/A

[#160614085] Fix display of inaccurate data and refactor styling

---

src/components/User/UserComponent.jsx

Fixes the inaccurate number of assigned assets being displayed on the user table
```gherkin
Scenario: An admin should see the accurate number of assigned assets.
Given an admin with access
When I visit the user page
Then I should see accurate data on the assigned assets column
```
* Log in
* Navigate to the users page
* View the number of assigned assets in the assigned asset column to confirm if the numbers shown are accurate
[161053181](https://www.pivotaltracker.com/story/show/161053181)
N/A
N/A
N/A
N/A
N/A

[#161053181] Fix inaccurate number of assigned assets displayed on the user table

---

src/__test__/AssetsComponent.test.js
src/__test__/AssetsTableContent.test.js
src/__test__/PaginationComponent.test.js
src/__test__/_components/AssetsContainer.test.js
src/__test__/components/FilterButton.test.js
src/__test__/components/FilterComponent.test.js
src/_components/Assets/AssetsContainer.jsx
src/_components/RoutesComponent.jsx
src/_css/AssetsComponent.scss
src/_css/LoaderComponent.scss
src/_css/PaginationComponent.scss
src/_mock/filters.js
src/components/AssetsComponent.jsx
src/components/AssetsTableContent.jsx
src/components/LoaderComponent.jsx
src/components/common/FilterButton.jsx
src/components/common/PaginationComponent.jsx

Makes changes to the loading spinner on the assets page as a UI improvement
- Make changes to the relevant components to enable the loading spinner to only cover the table
- The title as well as filter button (disabled during loading) should both show as the loader spins
- Pagination should be visible as the loader spins as well expect during the first load
Once logged in, navigate to `assets`, observe the difference in the loader UI. Navigate to page 2 to view the pagination below the loading spinner as well.
[#161281468](https://www.pivotaltracker.com/n/projects/2146417/stories/161281468)
N/A
N/A
N/A
N/A
Branch | PR
- First time load (filter button disabled and pagination not visible)
- After loading (filter …

[#161281468] Only show full page loading  spinner when loading assets

---

src/components/User/UserDetailComponent.jsx

Makes the asset list on user details page clickable.
```gherkin
Scenario: Asset list on user details page
Given A logged in user
When I visit the user details page
And I click on one of the assets assigned to that user
Then I should see the details of that asset.
```
* Log in
* Click on the `Users` link
* Click on one of the users that have assets assigned to them
* Click on one of the assets and you should be redirected to the asset's detail page
[162248159](https://www.pivotaltracker.com/story/show/162248159)
N/A
N/A
N/A
N/A
N/A

#162248159 Add a link on the asset table row

---

src/__test__/components/AssetDescriptionComponent.test.js
src/__test__/components/AssignAssetComponent.test.js
src/__test__/reducers/asset.reducer.test.js
src/_actions/asset.actions.js
src/_constants/index.js
src/_css/ModalComponent.scss
src/_reducers/asset.reducer.js
src/components/AssetDescriptionComponent.jsx
src/components/AssignAssetComponent.jsx
src/components/common/ConfirmAction.jsx
src/components/common/ModalComponent.jsx

Fixes a bug where if an asset was damaged or lost, it would still render the asset allocation dropdown but fail to assign the asset since only available assets can be assigned. 
```gherkin
Scenario: An asset can only be assigned if its status is `Available`.
Given a damaged or lost asset
When I want to assign it 
Then I should see a message telling me that only available assets can be assigned.
```
* Log in to the app
* Click the Assets link
* Select an asset whose status is either damaged or lost. You should be presented with a message instead of the dropdown
[162341806](https://www.pivotaltracker.com/story/show/162341806)
N/A
* Added some tweaks to improve the modal aesthetics
N/A
N/A
N/A

#162341806 Fix asset assignment bug

---

src/__test__/actions/asset.actions.test.js
src/components/AssetsTableContent.jsx

- Shows the email (or full name) of user that an asset is assigned to
- Admin can see user assigned to asset on asset list page
- Removes category and sub-category columns from assets list table
- Go to the assets list page. On the table you should see the email (or full name) of a user that an asset has been assigned to
https://www.pivotaltracker.com/story/show/162248110
N/A
N/A
N/A
N/A
Branch | PR

Admin can see user assigned to asset 162248110

---

src/components/AssetsTableContent.jsx

Fixes asset assigned to non email assignees showing as `undefined` in asset list table
Same as 👆🏽
The `assigned_to` column on the assets list table should no longer show `undefined`
https://www.pivotaltracker.com/story/show/162481628
Branch | PR

bg fix asset assigned to non email assignees showing as undefined in asset list table

---

src/components/AssetsComponent.jsx
src/components/AssetsTableContent.jsx

Applies filters after pagination change
Ensure that after pagination change, filters are still applied if there any
Go to the assets list table and apply a filter. Then change to another page, filter(s) should still be applied after pagination change
https://www.pivotaltracker.com/story/show/162474348
N/A
Branch | PR

Bg filters unapplied after pagination 162474348

---

src/_actions/users.actions.js
src/_components/User/UserContainer.jsx
src/_utils/constructUrl.js
src/components/User/UserComponent.jsx

Retains the filters applied even after row change
- Refactor `retrieveUsers` within UserComponent
- Head on to the `User List` page, click on the filter button to filter by any option of choice. 
- Click on the pagination row change drop down to change the number of rows being displayed. You should see users under the filter option you applied at the beginning.
[#162500589](https://www.pivotaltracker.com/n/projects/2146417/stories/162500589)
N/A
N/A
N/A
N/A
Branch | PR
N/A

bug(user-filter): keep filters applied after row change

---

src/_components/RoutesComponent.jsx

Moves the `assets/create` before `assets/:status?`
Clicking the `Add Asset` button was rendering the "not found" UI instead of the necessary form. This PR fixes the issue
- Click `Add Asset` button and ensure that the form gets rendered
- Verify that `/assets/allocated`, `/assets`, `/assets/lost`, etc routes still work as intended
https://www.pivotaltracker.com/n/projects/2146417/stories/162637155
**Before**
**After**
Branch | PR

Make the create asset route come before the optional one

---

src/__test__/_components/AddAssetContainer.test.js
src/__test__/components/FilterAssetComponent.test.js
src/_components/Assets/AddAssetContainer.jsx
src/components/Assets/FilterAssetComponent.jsx

Hides device specifications step (in the add assets page) if an asset does not have any specs
Same as ☝🏾
On the `Add assets` page select an asset that has `has_specs = false`, the device specifications step should be hidden
https://www.pivotaltracker.com/n/projects/2146417/stories/161678740
N/A
Branch | PR

Ft Hide device spec step if has_spec is false

---

src/__test__/components/AssetVerifiedComponent.test.js
src/_css/AssetDetailsComponent.scss
src/components/AssetDetails/AssetDetailsComponent.jsx
src/components/AssetDetails/AssetVerifiedComponent.jsx
src/components/common/CheckboxComponent.jsx
src/components/common/DropdownComponent.jsx

Enables an Admin to mark assets as verified/unverified
- add AssetVerifiedStatusComponent
- add css styling
- add relevant tests
Head on to the `Assets List` page, click on a single asset, on the field labeled `Verified` click on the edit button to change its status to verified or unverified.
[#162078804](https://www.pivotaltracker.com/n/projects/2146417/stories/162078804)
N/A
N/A
N/A
N/A
Branch | PR

feat(assets): admin can mark assets as verified/unverified

---

package-lock.json
src/_css/AssetDetailsComponent.scss
src/components/User/UsersContent.jsx
src/components/User/UsersTabComponent.jsx

Enables scrolling on the different tabs on the asset details page.
```gherkin
Scenario: Enable scrolling  on asset details
Given an admin with access
When I view the asset details  i.e Description, Notes, Allocation history 
Then I should be able to scroll through the details
When the list is long.
```
* Log in
* Click on the `Assets` link on the navigation bar
* Click on one of the assets to view its details
* If the content in any of the tabs is long enough, then you should be able to scroll it
[161212499](https://www.pivotaltracker.com/story/show/161212499)
N/A
Scrolling has been enabled for all tabs and not just the `Allocation history` tab
N/A
N/A
N/A

#161212499 Enable scrolling on asset details

---

package.json
src/__test__/components/AssetsComponent.test.js
src/components/AssetsComponent.jsx

Shows `Filter` button even when there are no assets so user does not have to reload the page to re-apply filters
Same as ☝🏽
Apply filters on the assets list page for `Magic Keyboard` even though it's an empty list the `Filter` button should still be visible so you can reapply another filter
https://www.pivotaltracker.com/story/show/162696252
N/A
N/A
N/A
Branch | PR

Bg-Fetching assets

---

src/components/SecurityUser/AddSecurityUserComponent.jsx

Fixes a bug in the security user creation form
```
The add security user form does not submit even when the details entered are correct.
```
* Log in
* Click on the `Users` link on the navigation bar
* Click on the `Security Users` tab
* Click on the `ADD SECURITY USER` button to open the modal
* Fill in security user details and submit the form
[163756068](https://www.pivotaltracker.com/story/show/163756068)
N/A
N/A
N/A
N/A
N/A
N/A

#163756068 Fix add security user form submission

---

src/__test__/AllocationComponent.test.js
src/__test__/TableRowComponent.test.js
src/__test__/_components/AssetsContainer.test.js
src/__test__/components/AssetModelsComponent.test.js
src/__test__/components/AssetsSubCategoriesComponent.test.js
src/_components/Assets/AssetsContainer.jsx
src/_mock/filters.js
src/_reducers/checkedFilters.reducer.js
src/_utils/assets.js
src/components/AssetsComponent.jsx
src/components/AssetsTableContent.jsx
src/components/TableRowComponent.jsx
src/components/common/Filter/FilterButton.jsx
src/components/common/Filter/FilterComponent.jsx

Enables a user to filter assets by either verified or unverified.
Add verified/unverified as filter options.
Add functionality to enable filters to be applied
Head on to the Assets list page, click on the filter button to view all options. Filter by either verified or unverified.
[#162780351](https://www.pivotaltracker.com/n/projects/2146417/stories/162780351)
N/A
The task is not complete. One can only filter by either verified and unverified but not both.
N/A
N/A
Branch | PR

[162780351] Filter verified unverified assets

---

src/__test__/actions/securityUsers.actions.test.js
src/_actions/securityUsers.actions.js
src/components/common/Filter/FilterButton.jsx

- indicates active filter selection
- Update the security user Model to include the status(bool inactive/active.
- Apply filter on security users and check if the applied filter is still indicated
- [#163019536](https://www.pivotaltracker.com/story/show/163019536)

chore(filters):  security users filter

---

src/__test__/_components/AssetsContainer.test.js
src/__test__/actions/assets.action.test.js
src/__test__/components/AssetsComponent.test.js
src/__test__/reducers/assets.reducer.test.js
src/_actions/assets.action.js
src/_components/Assets/AssetsContainer.jsx
src/_components/RoutesComponent.jsx
src/_reducers/assets.reducer.js
src/_utils/assets.js
src/components/AssetsComponent.jsx
src/components/NavBarComponent.jsx

- Fix the bug to reload asset after searching
After searching an asset, 
- back buttons should go to the previous list of assets.
- Assets tab should fetch the list of assets.
Branch | PR

bug: fetch assets after search
