- .github/.gitmessage
Sets up a gitmessage template
- Sets up commit template for the project.
- Add files to staging area using `git add .`
- Press `git commit` to trigger the commit template.
[#157477485](https://www.pivotaltracker.com/story/show/157477485)
N/A
N/A
> #157477485 Setup gitmessage template 

- .github/pull_request_template.md
Sets up a pull request template
Currently, there isn't a pull request template. This PR sets up a pull request template.
N/A
[#157477450](https://www.pivotaltracker.com/story/show/157477450)
N/A
N/A
> #157477450 Setup pull request template

- .circleci/config.yml
- README.md
- Integrates Circle CI
- Integrate Circle CI
- Commit a change.
- Push the change
- Raise a PR for the change
[#157340050](https://www.pivotaltracker.com/story/show/157340050)
- Nil
- Nil
- Nil
- Nil
- Nil
- Nil
- Nil
> #157340050 Integrate Circle CI

- .gitignore
- package.json
- src/__test__/NavBarComponent.test.js
- src/__test__/SideMenuComponent.test.js
- src/_components/NavBarComponent.jsx
- src/_components/SideMenuComponent.jsx
- src/_css/NavBarComponent.css
- src/_css/SideMenuComponent.css
* Add a side menu for navigation links
* Add a navigation bar
* Implement a side menu to hold links to specific pages
* Implement a navigation bar to show page title and the username of the logged in user
* N/A
[157803964](https://www.pivotaltracker.com/story/show/157803964)
N/A
* Any component that is intended to have the side menu should be wrapped between `<SideMenuComponent></SideMenuComponent>`
* jsonwebtoken
N/A
> #157803964 Add side menu

- src/__test__/DashboardComponent.test.js
- src/_reducers/index.js
Remove duplicate import in _reducers/index.js
- Remove duplicate imports in reducer
- Fix failing test in Dashboard.test.js
- `npm run start`
- `npm test`
[#158105561](https://www.pivotaltracker.com/story/show/158105561)
n/a
n/a
n/a
n/a
Branch | PR
> [#158105561] Remove duplicate import in reducers

- src/components/AssetTypesComponent.jsx
- src/components/AssetsComponent.jsx
- src/components/TableRowComponent.jsx
It makes the TableRowComponent re-usable
- extract TableRowComponent
- import the TableRowComponent and pass in the table data and headings as props
[#157997180](https://www.pivotaltracker.com/story/show/157997180)
N/A
N/A
N/A
N/A
Branch | PR
N/A
> #157997180 Extract TableRowComponent

- .circleci/config.yml
- package-lock.json
- package.json
Fixes Cirlcle CI's config test command to be separate from the coveralls command
- Add new script for coverall
- Change current test command not to include coveralls
N/A
[#158106666](https://www.pivotaltracker.com/story/show/158106666)
- Coveralls is not showing accurate coverage since the default branch is currently Master and all PRs are being merged to develop
N/A
N/A
N/A
Branch | PR
> bg(coveralls)Fix coveralls script

- .eslintrc
- package-lock.json
- package.json
- Configure eslint.
- Set-up eslint rules in the repo.
- When ES6 syntax error is committed.
- The error is flagged by the IDE.
- [#158066168](https://www.pivotaltracker.com/story/show/158066168)
- Nil
- Nil
- eslint
- eslint-config-airbnb
- eslint-plugin-import
- eslint-plugin-jsx-a11y
- eslint-plugin-react
- Nil
Branch | PR
- Nil
> #158066168 Configure Eslint

- .hound.yml
- Integrates HoundCI to the project
- Integrate HoundCI 
- Style violations are pointed out when PRs are raised
[#158076113](https://www.pivotaltracker.com/story/show/158076113)
- Nil
- Nil
- Nil
- Nil
Branch | PR
- Nil
> #158076113 Integrate HoundCI

- .eslintrc
- package.json
Fix hound-ci error
- added some eslint rules to `.eslintrc`
- removed eslint-config-jest-enzyme
n/a
n/a
n/a
n/a
n/a
n/a
Branch | PR
> Chore: Add eslint rules and remove others

- .eslintrc
- .stylelintrc
- package.json
- fix eslint rules
- fix eslintrc rules
- remove prettier precommit hook from running
- add stylelint indentation rules
n/a
n/a
n/a
n/a
n/a
n/a
Branch | PR
>  Chore: Add, Fix and Remove some eslint rules

- src/_actions/asset.actions.js
- src/_actions/assetType.action.js
- src/_components/NavBarComponent.jsx
- src/_components/RoutesComponent.jsx
- src/components/LoginComponent.jsx
- src/index.js
- adds token to all outgoing requests
- Given a request to an API endpoint
- When the request is sent
- Then it should contain the token ID of the logged in user on the request headers
- visit a specific route and check the request headers for authorization token
- [#157340057](https://www.pivotaltracker.com/story/show/157340057)
- nil
- nil 
- none
- nil
Branch | PR
nil
> #157340057  All outgoing requests should contain token

- .eslintrc
- src/_components/NavBarComponent.jsx
Fixes logout button bug. Clicking the logout button now redirects to `login` page and removes the token from local storage. 
Fix issue with Logout Button
Click the logout button. You should not able to access the protected routes unless you log in again
#158288797
N/A
Branch | PR
> Ch fix logout button 158288797

- .eslintrc
- src/components/LoaderComponent.jsx
Create Loader for Asynchronous requests
#158288747
Branch | PR
> Ft:  Create loader 158288747

- src/__test__/LoginComponent.test.js
- src/_components/SideMenuComponent.jsx
- src/_css/LoginComponent.css
- src/components/LoginComponent.jsx
- Loads Cloudinary assets over https
- Cloudinary assets should be loaded over https and not http
N/A
[#158242424](https://www.pivotaltracker.com/story/show/158242424)
N/A
N/A
N/A
Branch | PR
> Bug: load Cloudinary over https

- src/_components/RoutesComponent.jsx
- src/components/LoginComponent.jsx
Redirects a user to the dashboard if they are logged in.
When a logged in user tries to access the root url, they are redirected back to the dashboard.
* Visit the root url and log in
* Load the root url again
[158242466](https://www.pivotaltracker.com/story/show/158242466)
N/A
N/A
N/A
N/A
N/A
N/A
> Bug: Redirect to dashboard if logged in

- src/__test__/LoginComponent.test.js
- src/__test__/NavbarComponent.test.js
- src/_components/NavBarComponent.jsx
- src/_css/NavBarComponent.css
- src/_mock/localStorage.js
- src/_utils/setAuthorizationConfig.js
- src/components/LoginComponent.jsx
- src/firebase/auth.js
- src/firebase/index.js
- src/index.js
Refreshes the firebase token
- add a function that refreshes the token if it is expired.
- after an hour you try to make an API request without logging in again
[#158613660](https://www.pivotaltracker.com/story/show/158613660)
N/A
N/A
N/A
Branch | PR
> #158613660 Refresh firebase token

- src/_actions/assets.action.js
- src/components/AssetTypesComponent.jsx
- src/components/AssetsComponent.jsx
- src/components/UserFeedbackComponent.jsx
Update `assets` endpoint to `manage-assets`
- Update `assets` endpoint to `manage-assets`
- Fix error in the handlePaginationChange function for affected pages
Visit the assets page
[#158820395](https://www.pivotaltracker.com/story/show/158820395)
`assets` endpoint still exists but for non-admin users. Admin users now use `manage-assets` endpoint
Nil
Nil
Nil
Branch | PR
> #158820395 Update assets endpoint

- .circleci/config.yml
- dockerfile
- script/deploy.sh
- server
**What does this PR do?**
Creates a continuous integration and delivery  pipeline 
**Description of Task to be completed?**
Once a feature is merged to develop or master branch it is automatically deployed to gcp
**What are the relevant pivotal tracker stories?**
[#156802464](https://www.pivotaltracker.com/story/show/156802464)
**Screenshots**
> #156802464 Implement automatic deployment to Google Cloud platform 

- src/__test__/AssetsAllocationHistory.test.js
- src/_css/AssetDetailContent.css
- src/components/AssetAllocationHistory.jsx
- src/components/AssetDetailContent.jsx
It displays an asset's allocation history
```
Scenario: asset allocation history
Given A logged in admin
When I visit the asset details page
And I click on the allocation history tab
Then I should see the asset allocation history
```
Once logged in, go to the assets page. Click on view icon of any asset, then click on the Asset Allocation history tab. If an asset has any allocation history, a table with these information will be displayed else ` Allocation history is not available for this asset` will be displayed.
https://www.pivotaltracker.com/story/show/159022593
N/A
N/A
N/A
N/A
Branch | PR
> Ft admin can see asset allocation history 159022593

- src/__test__/CardComponent.test.js
- src/_components/AuthenticateComponent.jsx
- src/_css/DashboardComponent.scss
- src/_css/LoginComponent.scss
- src/_css/ModalComponent.scss
- src/components/BarlineGraphComponent.jsx
- src/components/LoaderComponent.jsx
- src/components/PieChartComponent.jsx
Fixes hound errors existing in develop
There are [49 violations found](https://github.com/AndelaOSP/art-dashboard/pull/99)  raised by HoundCI that were probably in develop before the integration was done.
Adding this task to clean this up.
N/A
https://www.pivotaltracker.com/story/show/159528177
N/a
N/a
N/a
N/a
Branch | PR
> #159528177 Fix hound errors in develop

- src/__test__/components/NavBarComponent.test.js
- src/_css/NavBarComponent.scss
- src/components/AssetsTableContent.jsx
- src/components/NavBarComponent.jsx
Replaces the `Close x` button on the navbar with a more suitable icon
Replace the `Close x` button on the navbar
* Start the application
* Log in
* Open and close the navbar on the dashboard to see the different icons
[159790171](https://www.pivotaltracker.com/n/projects/2146417/stories/159790171)
N/A
N/A
N/A
N/A
N/A
> #159790171 Replace close x button

- package.json
Fix https://circleci.com/gh/AndelaOSP/art-dashboard/1302
> Lock react-jsx-highcharts

- src/__test__/components/AddAssetComponent.test.js
- src/_components/Assets/AddAssetContainer.jsx
- src/components/Assets/AddAssetComponent.jsx
- Fix a bug when adding an asset
- Break off adding an asset and adding an asset spec
- Login to ART
- Click on `ADD ASSET` 
- Add relevant fields. 
- Click on `SAVE`. You should see a Success message when adding an asset.
[#160110741](https://www.pivotaltracker.com/story/show/160110741)
n/a
n/a
n/a
n/a
Branch | PR
> #160110741 Bug when adding an asset

- README.md
- Describes directory structure in the readme
- Describe folder structure in the Readme
-  View the readme
[https://www.pivotaltracker.com/story/show/160088642]( #160088642])
- None
>  #160088642 Describe folder structure

- src/_components/RoutesComponent.jsx
- src/components/NavBarComponent.jsx
Change existing urls to use hyphen instead of underscore
- change asset types url to use hyphen
- change asset models url to use hyphen
- Login to ART
- Navigate to asset types, the url should be `/asset-types`
- Navigate to asset models, the url should be `/asset-models`
[#160232872](https://www.pivotaltracker.com/story/show/160232872)
n/a
n/a
n/a
n/a
Branch | PR
> #160232872 Rename urls to be hyphenated

- src/_css/AssetsComponent.scss
- src/_css/NavBarComponent.scss
- src/_css/sharedStyling.scss
- src/components/NavBarComponent.jsx
> test small headers

- src/_css/NavBarComponent.scss
- src/components/Dashboard/DashboardComponent.jsx
- src/components/NavBarComponent.jsx
Removes unnecessary page links and fixes ui inconsistencies
- Rename reports to incident reports
- Remove all sublinks under Assets on the menu bar
- Link Assets on the menu to asset list
- Remove feedback page
- Remove asset conditions
- Log in
- View changes on the dashboard and navigation bar
[160192896](https://www.pivotaltracker.com/story/show/160192896)
N/A
N/A
N/A
N/A
N/A
N/A
> #160192896 Clean up pages

- src/_css/AssetsComponent.scss
- src/_css/DashboardComponent.scss
- src/_css/IncidenceReportsComponent.scss
- src/_css/NavBarComponent.scss
- src/_css/UserFeedback.scss
- src/_css/UsersComponent.scss
- src/_css/sharedStyling.scss
- src/components/NavBarComponent.jsx
Makes the menu bar static when scrolling a page
```gherkin
1. Go to any of the pages e.g Assets or Users  Page
2. Scroll to the bottom of the page
3. The menu bar moves with the home, assets, users tabs disappears.
The Menu bar should be static
The menu bar moves when you scroll to the bottom.
```
* Log in
* Navigate to any page with scrollable content eg: `/assets`
* Scroll to see the fixed menu bar
[161048142](https://www.pivotaltracker.com/story/show/161048142)
N/A
N/A
N/A
N/A
N/A
> [#161048142] Make menu bar static and refactor navigation bar

- src/__test__/AssetDetailComponent.test.js
- src/__test__/AssetDetailContent.test.js
- src/__test__/AssetTypesAction.test.js
- src/__test__/_components/AddAssetContainer.test.js
- src/__test__/components/FilterAssetComponent.test.js
- src/__test__/components/FilterComponent.test.js
- src/_components/AuthenticateComponent.jsx
- src/components/AssetAllocationHistory.jsx
- src/components/AssetDescriptionComponent.jsx
- src/components/AssetDetailComponent.jsx
- src/components/AssetDetailContent.jsx
- src/components/AssetMake/AddAssetMakeComponent.jsx
- src/components/AssetMake/AssetMakeComponent.jsx
- src/components/AssetSpecs/AssetSpecsComponent.jsx
- src/components/AssetTypes/AddAssetTypesComponent.jsx
- src/components/Assets/FilterAssetComponent.jsx
- src/components/AssetsComponent.jsx
- src/components/AssetsTableContent.jsx
- src/components/ModelNumber/ModelNumberComponent.jsx
- src/components/PageNotFoundComponent.jsx
- src/components/SubCategory/AddSubCategoryComponent.jsx
- src/components/User/UserComponent.jsx
- src/components/UserDetailsComponent.jsx
- src/components/common/CheckboxComponent.jsx
- src/components/common/FilterButton.jsx
- src/components/common/FilterComponent.jsx
- src/components/common/ModalComponent.jsx
Fixes console errors in tests
```
Looking at the failing tests in https://circleci.com/gh/AndelaOSP/art-dashboard/1993, 
most of them have console errors that need to be fixed. 
Please fix the cause of the errors and verify that there's no test with console errors
```
* Open a terminal
* Execute the command `npm run coverage`
[161173331](https://www.pivotaltracker.com/story/show/161173331)
N/A
N/A
N/A
N/A
N/A
> [#161173331] Refactor tests and components to remove console errors

- src/_actions/assetStatus.action.js
- src/_css/NavBarComponent.scss
- src/components/NavBarComponent.jsx
Shows the currently active link on the application
```gherkin
Scenario: Highlighting active tabs
Given an authorized admin
When I  select on any of the tabs on the navigation bar i.e assets  , users e.t.c
Then the active tab should be highlighted.
```
* Log in to the application
* Click on any link in the navigation bar to see it highlighted
[160140895](https://www.pivotaltracker.com/story/show/160140895)
N/A
N/A
N/A
N/A
N/A
> [#160140895] Refactor navigation link logic and styling to show active links

- src/__test__/_components/Authorize.test.js
- src/_components/AccessControl/AuthenticateComponent.jsx
- src/_components/AccessControl/Authorize.jsx
- src/_components/RoutesComponent.jsx
- src/components/LoginComponent.jsx
Restricts access to the app to users that have admin privileges only
```gherkin
Scenario: Only admins can access the site.
Given a user with no admin rights
When I login to the ART site
Then I  should see an error message 
And be redirected to the login page.
```
* Login to the application
* If you are not an admin user, you should see a modal telling you that you are not authorized to access the site
[160192048](https://www.pivotaltracker.com/story/show/160192048)
Admin privileges are defined on Firebase. Make sure that your user has the appropriate custom claims.
N/A
N/A
N/A
Branch | PR
> #160192048 Restrict access to admin users only

- src/__test__/_components/AssetsContainer.test.js
- src/__test__/actions/assets.action.test.js
- src/__test__/components/AssetsComponent.test.js
- src/_actions/assets.action.js
- src/_components/Assets/AssetsContainer.jsx
- src/_components/RoutesComponent.jsx
- src/_css/DashboardComponent.scss
- src/_css/sharedStyling.scss
- src/_reducers/assets.reducer.js
- src/_utils/assets.js
- src/components/AssetsComponent.jsx
- src/components/AssetsTableContent.jsx
- src/components/Dashboard/AssetStatusComponent.jsx
- src/components/PageNotFoundComponent.jsx
- src/components/common/ItemsNotFoundComponent.jsx
Enables a logged in user to view available assets when they click on the `Available Assets` card on the homepage
```gherkin
Scenario: An admin can view a list of available assets
Given an admin with access
When I click on the available assets card  on the homepage
Then I should see a full  page  overlay with rows  of available assets.
On clicking the the row  then  it should redirect you to the asset details page , passing along the data required (This means that you should not make an API call to get asset details)
```
* Log in
* Click on the `Available Assets` card. You should be redirected to a page displaying all the available assets
[161052506](https://www.pivotaltracker.com/story/show/161052506)
N/A
* The way I have implemented the logic for this task allows for any of the cards on …
> #161052506 View available assets

- src/__test__/components/TabsComponent.test.jsx
- src/_css/TabsComponent.scss
- src/components/common/TabsComponent.jsx
``` Creates a common Tabs component```
```Create a common Tab component to avoid code duplication.```
```Can only be tested once implemented in other components```
https://www.pivotaltracker.com/story/show/162574882
N/A
N/A
N/A
N/A
Branch | PR
> #162574882 Create a common tabs component 

- package-lock.json
Updates package lock file
N/A
N/A
N/A
I installed `jest-enzyme` in https://github.com/AndelaOSP/art-dashboard/pull/185 using `yarn` and forgot to update `package-lock.json`
N/A
N/A
N/A
Branch | PR
> Updated package lock

- src/_actions/officeLocations.actions.js
- src/_reducers/officeLocations.reducer.js
Includes `RESET_STATUS_MESSAGE` in officeLocations actions
- Add `resetMessage` actionType
N/A
[#162784568](https://www.pivotaltracker.com/n/projects/2146417/stories/162784568)
N/A
N/A
N/A
Branch | PR
N/A
> [#162784568] Bug Fix 

- src/__test__/_components/AddSecurityUserContainer.test.js
- src/__test__/actions/securityUsers.actions.test.js
- src/__test__/components/ActionComponent.test.js
- src/__test__/components/AddAssetMakeComponent.test.js
- src/__test__/components/AddAssetTypesComponent.test.js
- src/__test__/components/AddSecurityUserComponent.test.js
- src/__test__/components/AssetCategoriesComponent.test.js
- src/__test__/components/AssetMakesComponent.test.js
- src/__test__/components/AssetTypesAction.test.js
- src/__test__/components/AssetTypesComponent.test.js
- src/__test__/components/AssetsSubCategoriesComponent.test.js
- src/__test__/components/ConfirmAction.test.js
- src/__test__/reducers/securityUsers.reducer.test.js
- src/_actions/securityUsers.actions.js
- src/_components/RoutesComponent.jsx
- src/_components/SecurityUser/AddSecurityUserContainer.jsx
- src/_css/ModalComponent.scss
- src/_reducers/securityUsers.reducer.js
- src/components/AssetMake/AddAssetMakeComponent.jsx
- src/components/AssetTypes/AddAssetTypesComponent.jsx
- src/components/Category/AddCategoryComponent.jsx
- src/components/ModelNumber/ModelNumberComponent.jsx
- src/components/SecurityUser/AddSecurityUserComponent.jsx
- src/components/SubCategory/AddSubCategoryComponent.jsx
- src/components/User/UsersComponent.jsx
Fixes the security users form
```
The modal should conform to the standard forms used throughout the dashboard.
```
* Log in
* Click on the `Users` link on the navigation bar
* Click on the `Security Users` tab
* Click on the `ADD SECURITY USER` button to see the modal
[162694165](https://www.pivotaltracker.com/story/show/162694165)
N/A
N/A
N/A
N/A
N/A
When the email is not valid before submitting data to the backend
When there is an error after submitting data to the backend
When data is submitted successfully without any errors
> #162694165 Fix security users form

- .circleci/config.yml
- package-lock.json
- package.json
Fixes security vulnerability with `react-scripts` package
Same as ☝🏾
Running npm audit should should show `found 0 vulnerabilities`
https://www.pivotaltracker.com/story/show/162696252
N/A
Branch | PR
> Ch-upgrade react-scripts to v2.1.3

- src/_reducers/securityUsers.reducer.js
- src/components/SecurityUser/AddSecurityUserComponent.jsx
- src/components/User/UsersComponent.jsx
Fixes the filter button on the User's page. Also fixes add security user button
Same as ☝🏾
On the User's page, the filter button and the add user button should be working
https://www.pivotaltracker.com/story/show/163046252
N/A
Branch | PR
> Bg-irresponsive user page buttons 163046252

- src/__test__/SessionExpiredComponent.test.js
- src/__test__/components/AssetCategoriesComponent.test.js
- src/__test__/components/AssetDescriptionComponent.test.js
- src/__test__/components/AssetMakesComponent.test.js
- src/__test__/components/AssetModelsComponent.test.js
- src/__test__/components/AssetTypesAction.test.js
- src/__test__/components/AssetTypesComponent.test.js
- src/__test__/components/AssetsSubCategoriesComponent.test.js
- src/__test__/components/UsersComponent.test.js
- src/_components/AccessControl/Authorize.jsx
- src/components/AssetDescriptionComponent.jsx
- src/components/AssetMake/AssetMakeComponent.jsx
- src/components/AssetModels/AssetModelsComponent.jsx
- src/components/AssetTypes/AssetTypesComponent.jsx
- src/components/AssetTypesAction.jsx
- src/components/Category/AssetCategoriesComponent.jsx
- src/components/SessionExpiredComponent.jsx
- src/components/SubCategory/AssetsSubCategoriesComponent.jsx
- src/components/User/UsersComponent.jsx
- src/components/common/ModalComponent.jsx
Refactors the Modal component to a functional component.
Each component making use of the ModalComponent refactored to maintain the modalOpen state
Modals should work the same way they did prior to refactoring
N/A
N/A
N/A
N/A
N/A
Branch | PR
N/A
> [Chore] Refactoring the ModalComponent

- docs/user_workflow.md
Make minor changes to regression document
Branch | PR
> Minor changes to regression document

- src/_components/NavBarContainer.jsx
- src/_utils/assets.js
- src/components/NavBarComponent.jsx
It enables an Admin user to search and filter assets by serial numbers
Filter the assets in the assets table by its serial number.
In the navigation bar located the search field, input the number you want to search for, then click the return or enter key.
[#163556763](https://www.pivotaltracker.com/story/show/163556763)
N/A
N/A
N/A
N/A
Branch | PR
> [#163556763] search assets by serial number

- README.md
- docs/regression_workflow.md
- docs/user_workflow.md
Adds a document for the app's regression workflow
```
Create a document to record user workflows within the application. The data recorded on this document will be used when setting up regression and end to end tests.
```
N/A
[163723531](https://www.pivotaltracker.com/story/show/163723531)
N/A
This document is to be populated on a regular basis until all possible workflows are covered
N/A
N/A
N/A
N/A
> #163723531 Add regression workflow document

- src/components/SecurityUser/AddSecurityUserComponent.jsx
Ensures user emails are converted to lowercase before sending to the backend
N/A
- Create a new security user with Email Capitalized and load security users
[#163514301](https://www.pivotaltracker.com/story/show/163514301)
N/A
N/A
N/A
N/A
Branch | PR
> Feat(162780351): Convert user emails to Lower case

- src/__test__/_components/SecurityUserFilterContainer.test.js
- src/__test__/components/FilterButton.test.js
- src/__test__/reducers/checkedFilters.reducer.test.js
- src/_actions/securityUsers.actions.js
- src/_components/User/SecurityUserFilter.js
- src/_components/User/UserFilterContainer.jsx
- src/_mock/filters.js
- src/_reducers/checkedFilters.reducer.js
- src/components/User/UsersComponent.jsx
- src/components/common/Filter/FilterButton.jsx
- filters security users by activity status (active, inactive)
`` Scenario: Filter security users by status
Given Admin with access
When I click on the filter user's button i.e active, inactive.
Then I should see results with filters applied. ``
- on security users tab under users click filter button and select active to be either true or false
- [#163019536](https://www.pivotaltracker.com/story/show/163019536)
> Filter security users

- src/__test__/components/AssetLogComponent.test.js
- src/_css/ActionComponent.scss
- src/_css/AssetLogComponent.scss
- src/_mock/assetLogs.js
- src/components/AssetLogs/AssetLogComponent.jsx
Displays Checked in and checkout out logs of an asset on a Single row
[#163048333](https://www.pivotaltracker.com/story/show/163048333)
N/A
Branch | PR
> Feat(163048333): Display Checkin and Checkout logs

- src/__test__/actions/assets.action.test.js
- src/__test__/components/AssetsComponent.test.js
- src/__test__/components/ExportAsset.test.js
- src/_actions/assets.action.js
- src/components/Assets/ExportAsset.jsx
- src/components/AssetsComponent.jsx
It enables Assets export to file based on status.
Export assets depending on status.
- Navigate to the asset list page based on status (lost, damages, allocated, available)
- Click the Export to File button
- Click on the download link available on the modal
[#164983578](https://www.pivotaltracker.com/story/show/164983578)
- Nil
- Nil
- Nil
- Nil
Branch | PR
> [#164983578]: Enable Asset Export to File
